import yaml
import sys
import commands
from itertools import groupby
from operator import itemgetter

if (len(sys.argv) != 3):
	print "Invalid number of arguments"
	sys.exit(0)

wd = str(sys.argv[1])
env = str(sys.argv[2])
env_path = wd + '/group_vars/' + env
tf_file = wd + '/roles/terraform/meta/' + env + '/terraform.tf'
nodes_file = env_path + '/nodes.yml'

node_stream = open(nodes_file, "r")
nodes = yaml.load(node_stream)

file = open(tf_file, 'w')
file.write('## Autogenerated by Ansible\n\n\
provider "scaleway" {\n\
\ttoken = "<API_TOKEN>"\n\
\torganization = "<ORGANIZATION_KEY>"\n\
\tregion = "par1"\n\
}\n');

# Print private ip in nodes.yml
for node in nodes['nodes']:
	node_data = nodes['nodes'][node]

	file.write('resource "scaleway_server" "'+node+'" {\n\
	  \tname = "'+node_data['fqdn']+'"\n\
	  \timage = "7069f3d0-23e3-4664-8f6b-1a17ed478dff"\n\
	  \ttype = "'+node_data['flavor']+'"\n\
	  \ttags = [\"terraformed\"]\n\
	  \tdynamic_ip_required = true\n')

	for disk in node_data['disks']:
		if (disk['volume']):
			file.write('\tvolume {\n\
    			\t\tsize_in_gb = '+str(disk['size'])+'\n\
    			\t\ttype = "'+disk['type']+'"\n\
  				\t}\n')

	file.write('}\n')
